# Don't print a new line at the start of the prompt
add_newline = false

#directory module
[directory]
#prefixStyle = "#ffffdd"
#pathStyle = "#5555dd"
format="[‚ï≠‚ï¥](#D7E8BA) [$path](#FFCF3C) [$read_only]($read_only_style)"

# Replace the "‚ùØ" symbol in the prompt with "Œª"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[‚ï∞‚ï¥](#D7E8BA)[Œª](#4DA1A9)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
error_symbol = "[‚ï∞‚ï¥](#D7E8BA)[Œî](#2E5077)"
# "[‚ï∞‚ï¥](yellow)"

[memory_usage]
disabled = false
symbol = "üß†"
style = "#084C61"

[git_branch]
style = "#5F8DD3"

[python]
python_binary = "python3"

[git_status]
style = "#87DEAA"
#Disable the package module, hiding it from the prompt completely
